<a href="https://colab.research.google.com/github/Deepmidnight/Midnight_nebula/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_Python_%D0%98%D1%82%D0%BE%D0%B3%D0%BE%D0%B2%D0%B0%D1%8F_BigData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd


column_names_data = ['user id', 'item id', 'rating', 'timestamp']
column_names_item = ['movie id', 'movie title', 'release date', 'video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure', 'Animation', "'Children's'", 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']


ratings = pd.read_csv('u.data.csv', encoding='ISO-8859-1', sep = '\t', names=column_names_data)
movies = pd.read_csv('u.item.csv', encoding='ISO-8859-1', sep = '|', names=column_names_item)

# 1. Загрузите в колаб файлы по оценкам (ratings) и фильмам (movies) и создайте на их основе pandas-датафреймы

In [ ]:
ratings.head()

   user id  item id  rating    timestamp
0      196      242     3.0  881250949.0
1      186      302     3.0  891717742.0
2       22      377     1.0  878887116.0
3      244       51     2.0  880606923.0
4      166      346     1.0  886397596.0

In [ ]:
movies.head()

,movie id,movie title,release date,video release date,IMDb URL,unknown,Action,Adventure,Animation,'Children's',...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
df_merged = ratings.merge(movies, left_on='item id', right_on='movie id', how='inner')
df_merged.drop('item id', axis=1, inplace=True)
df_merged.sort_values('movie id').head()

,user id,rating,timestamp,movie id,movie title,release date,video release date,IMDb URL,unknown,Action,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
1791,5,4.0,875635748.0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,...,0,0,0,0,0,0,0,0,0,0
1870,242,4.0,879740362.0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,...,0,0,0,0,0,0,0,0,0,0
1869,490,3.0,875427148.0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,...,0,0,0,0,0,0,0,0,0,0
1868,101,3.0,877136039.0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,...,0,0,0,0,0,0,0,0,0,0
1867,243,4.0,879987239.0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,...,0,0,0,0,0,0,0,0,0,0

# 2. Средствами Pandas, используя dataframe ratings, найдите id пользователя, поставившего больше всего оценок

In [ ]:
rating_filter = ratings[['user id', 'rating']]
rating_filter.head()

   user id  rating
0      196     3.0
1      186     3.0
2       22     1.0
3      244     2.0
4      166     1.0

In [ ]:
grouped = rating_filter.groupby('user id').count()
grouped.sort_values('rating', ascending=False).head()

         rating
user id
405         534
13          490
276         413
234         377
303         372

In [ ]:
max_ = grouped['rating'].max()
max_id = grouped[grouped['rating'] == grouped['rating'].max()]
max_id

         rating
user id
405         534

# 3.Оставьте в датафрейме ratings только те фильмы, который оценил данный пользователь

In [ ]:
user_filter = ratings[['user id', 'rating', 'item id']]
user_filter

       user id  rating  item id
0          196     3.0      242
1          186     3.0      302
2           22     1.0      377
3          244     2.0       51
4          166     1.0      346
...        ...     ...      ...
53149      642     3.0     1311
53150      405     4.0       29
53151      151     4.0      614
53152      592     2.0      678
53153      194     NaN        2

[53154 rows x 3 columns]

In [ ]:
max_user_filter = user_filter.loc[user_filter['user id'] == 405]
max_user_filter

       user id  rating  item id
12276      405     4.0       56
12383      405     1.0      592
12430      405     1.0     1582
12449      405     1.0      171
12460      405     1.0      580
...        ...     ...      ...
52708      405     1.0      921
52790      405     1.0       42
53031      405     3.0      231
53096      405     4.0      728
53150      405     4.0       29

[534 rows x 3 columns]

# 4.Добавьте к датафрейму из задания 3 столбцы:
- По жанрам. Каждый столбец - это жанр. Единицу записываем, если фильм принадлежит данному жанру и 0 - если нет
- Cтолбцы с общим количеством оценок от всех пользователей на фильм и суммарной оценкой от всех пользователей

In [ ]:
user_filter_count = max_user_filter
user_filter_count['Count rating'] = ratings.groupby(by='item id')['rating'].transform('count')
user_filter_count['Sum rating'] = ratings.groupby(by='item id')['rating'].transform('sum')
user_filter_count

<ipython-input-57-8ed7650188b3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  user_filter_count['Count rating'] = ratings.groupby(by='item id')['rating'].transform('count')
<ipython-input-57-8ed7650188b3>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  user_filter_count['Sum rating'] = ratings.groupby(by='item id')['rating'].transform('sum')

       user id  rating  item id  Count rating  Sum rating
12276      405     4.0       56           220       915.0
12383      405     1.0      592             5        15.0
12430      405     1.0     1582             1         1.0
12449      405     1.0      171            35       140.0
12460      405     1.0      580            16        51.0
...        ...     ...      ...           ...         ...
52708      405     1.0      921            28       111.0
52790      405     1.0       42            85       323.0
53031      405     3.0      231            76       202.0
53096      405     4.0      728            26        77.0
53150      405     4.0       29            58       164.0

[534 rows x 5 columns]

In [ ]:
df_user_filter_merged = user_filter_count.merge(movies, left_on='item id', right_on='movie id', how='inner')
df_user_filter_merged.drop('movie id', axis=1, inplace=True)

import numpy as np
df_user_filter_merged['unix date'] = pd.to_datetime(df_user_filter_merged['release date']).astype(np.int64)

df_user_filter_merged = df_user_filter_merged[['user id', 'rating',	'item id',	'Count rating',	'Sum rating',	'release date','unix date', 'Action', 'Adventure', 'Animation', "'Children's'", 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']]
df_user_filter_merged

<ipython-input-58-00a15ada63ee>:5: FutureWarning: casting datetime64[ns] values to int64 with .astype(...) is deprecated and will raise in a future version. Use .view(...) instead.
  df_user_filter_merged['unix date'] = pd.to_datetime(df_user_filter_merged['release date']).astype(np.int64)

,user id,rating,item id,Count rating,Sum rating,release date,unix date,Action,Adventure,Animation,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,405,4.0,56,220,915.0,01-Jan-1994,757382400000000000,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,405,1.0,592,5,15.0,01-Jan-1995,788918400000000000,0,0,0,...,0,0,0,0,1,0,0,1,0,0
2,405,1.0,1582,1,1.0,01-Jan-1947,-725846400000000000,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,405,1.0,171,35,140.0,01-Jan-1991,662688000000000000,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,405,1.0,580,16,51.0,01-Jan-1995,788918400000000000,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
529,405,1.0,921,28,111.0,01-Jan-1993,725846400000000000,0,0,0,...,0,0,0,0,0,1,0,0,0,0
530,405,1.0,42,85,323.0,01-Jan-1994,757382400000000000,0,0,0,...,0,0,0,0,0,0,0,0,0,0
531,405,3.0,231,76,202.0,01-Jan-1992,694224000000000000,1,1,0,...,0,0,0,0,0,0,0,0,0,0
532,405,4.0,728,26,77.0,01-Jan-1994,757382400000000000,0,0,0,...,0,0,0,0,0,0,1,0,0,0
533,405,4.0,29,58,164.0,01-Jan-1995,788918400000000000,1,1,0,...,0,0,0,0,0,0,0,0,0,0

# 5.Сформируйте X_train, X_test, y_train, y_test

In [ ]:
X, y = df_user_filter_merged [['Count rating',	'Sum rating',	'unix date', 'Action', 'Adventure', 'Animation', "'Children's'", 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']], df_user_filter_merged['rating']

In [ ]:
X.head()

,Count rating,Sum rating,unix date,Action,Adventure,Animation,'Children's',Comedy,Crime,Documentary,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,220,915.0,757382400000000000,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,5,15.0,788918400000000000,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
2,1,1.0,-725846400000000000,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,35,140.0,662688000000000000,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
4,16,51.0,788918400000000000,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0

In [ ]:
y.head()

0    4.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: rating, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
X_train.head()

,Count rating,Sum rating,unix date,Action,Adventure,Animation,'Children's',Comedy,Crime,Documentary,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
6,12,43.0,788918400000000000,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
0,220,915.0,757382400000000000,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
21,137,536.0,315532800000000000,1,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
210,42,126.0,757382400000000000,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
245,215,919.0,662688000000000000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
y_train.head()

6      3.0
0      4.0
21     5.0
210    3.0
245    4.0
Name: rating, dtype: float64

# 6.Возьмите модель линейной регрессии (или любую другую для задачи регрессии)  и обучите ее на фильмах

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

# 7.Оцените качество модели на X_test, y_test при помощи метрик для задачи регрессии:

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
mean_squared_error(y_train, model.predict(X_train))

13.961243596409334

In [ ]:
mean_squared_error(y_test, model.predict(X_test))

15.82459218319339

# Spark

# 8.Загрузить данные в spark

In [ ]:
!apt-get update

Hit:1 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease
Ign:2 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:3 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Hit:7 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:9 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Hit:10 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Hit:11 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Hit:13 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Reading package lists... Done

In [ ]:
!apt-get install openjdk-8-jdk-headless -qq > /dev/null

In [ ]:
!wget -q https://downloads.apache.org/spark/spark-3.2.3/spark-3.2.3-bin-hadoop2.7.tgz

In [ ]:
!tar -xvf spark-3.2.3-bin-hadoop2.7.tgz

spark-3.2.3-bin-hadoop2.7/
spark-3.2.3-bin-hadoop2.7/LICENSE
spark-3.2.3-bin-hadoop2.7/NOTICE
spark-3.2.3-bin-hadoop2.7/R/
spark-3.2.3-bin-hadoop2.7/R/lib/
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/DESCRIPTION
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/INDEX
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/Meta/
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/Meta/Rd.rds
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/Meta/features.rds
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/Meta/hsearch.rds
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/Meta/links.rds
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/Meta/nsInfo.rds
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/Meta/package.rds
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/NAMESPACE
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/R/
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/R/SparkR
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/R/SparkR.rdb
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/R/SparkR.rdx
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/help/
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/help/AnIndex
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/help/SparkR.rdb
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/help/SparkR.rdx
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/help/aliases.rds
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/help/paths.rds
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/html/
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/html/00Index.html
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/html/R.css
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/profile/
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/profile/general.R
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/profile/shell.R
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/tests/
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/tests/testthat/
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/tests/testthat/test_basic.R
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/worker/
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/worker/daemon.R
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/worker/worker.R
spark-3.2.3-bin-hadoop2.7/R/lib/sparkr.zip
spark-3.2.3-bin-hadoop2.7/README.md
spark-3.2.3-bin-hadoop2.7/RELEASE
spark-3.2.3-bin-hadoop2.7/bin/
spark-3.2.3-bin-hadoop2.7/bin/beeline
spark-3.2.3-bin-hadoop2.7/bin/beeline.cmd
spark-3.2.3-bin-hadoop2.7/bin/docker-image-tool.sh
spark-3.2.3-bin-hadoop2.7/bin/find-spark-home
spark-3.2.3-bin-hadoop2.7/bin/find-spark-home.cmd
spark-3.2.3-bin-hadoop2.7/bin/load-spark-env.cmd
spark-3.2.3-bin-hadoop2.7/bin/load-spark-env.sh
spark-3.2.3-bin-hadoop2.7/bin/pyspark
spark-3.2.3-bin-hadoop2.7/bin/pyspark.cmd
spark-3.2.3-bin-hadoop2.7/bin/pyspark2.cmd
spark-3.2.3-bin-hadoop2.7/bin/run-example
spark-3.2.3-bin-hadoop2.7/bin/run-example.cmd
spark-3.2.3-bin-hadoop2.7/bin/spark-class
spark-3.2.3-bin-hadoop2.7/bin/spark-class.cmd
spark-3.2.3-bin-hadoop2.7/bin/spark-class2.cmd
spark-3.2.3-bin-hadoop2.7/bin/spark-shell
spark-3.2.3-bin-hadoop2.7/bin/spark-shell.cmd
spark-3.2.3-bin-hadoop2.7/bin/spark-shell2.cmd
spark-3.2.3-bin-hadoop2.7/bin/spark-sql
spark-3.2.3-bin-hadoop2.7/bin/spark-sql.cmd
spark-3.2.3-bin-hadoop2.7/bin/spark-sql2.cmd
spark-3.2.3-bin-hadoop2.7/bin/spark-submit
spark-3.2.3-bin-hadoop2.7/bin/spark-submit.cmd
spark-3.2.3-bin-hadoop2.7/bin/spark-submit2.cmd
spark-3.2.3-bin-hadoop2.7/bin/sparkR
spark-3.2.3-bin-hadoop2.7/bin/sparkR.cmd
spark-3.2.3-bin-hadoop2.7/bin/sparkR2.cmd
spark-3.2.3-bin-hadoop2.7/conf/
spark-3.2.3-bin-hadoop2.7/conf/fairscheduler.xml.template
spark-3.2.3-bin-hadoop2.7/conf/log4j.properties.template
spark-3.2.3-bin-hadoop2.7/conf/metrics.properties.template
spark-3.2.3-bin-hadoop2.7/conf/spark-defaults.conf.template
spark-3.2.3-bin-hadoop2.7/conf/spark-env.sh.template
spark-3.2.3-bin-hadoop2.7/conf/workers.template
spark-3.2.3-bin-hadoop2.7/data/
spark-3.2.3-bin-hadoop2.7/data/graphx/
spark-3.2.3-bin-hadoop2.7/data/graphx/followers.txt
spark-3.2.3-bin-hadoop2.7/data/graphx/users.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/
spark-3.2.3-bin-hadoop2.7/data/mllib/als/
spark-3.2.3-bin-hadoop2.7/data/mllib/als/sample_movielens_ratings.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/als/test.data
spark-3.2.3-bin-hadoop2.7/data/mllib/gmm_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/images/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/license.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/kittens/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/kittens/29.5.a_b_EGDP022204.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/kittens/54893.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/kittens/DP153539.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/kittens/DP802813.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/kittens/not-image.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/license.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/multi-channel/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/multi-channel/BGRA.png
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/multi-channel/BGRA_alpha_60.png
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/multi-channel/chr30.4.184.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/multi-channel/grayscale.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-01/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-01/29.5.a_b_EGDP022204.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-01/not-image.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/54893.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/DP153539.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/DP802813.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-01/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-01/BGRA.png
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-01/BGRA_alpha_60.png
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-02/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-02/chr30.4.184.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-02/grayscale.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/iris_libsvm.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/kmeans_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/pagerank_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/pic_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/ridge-data/
spark-3.2.3-bin-hadoop2.7/data/mllib/ridge-data/lpsa.data
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_binary_classification_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_fpgrowth.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_isotonic_regression_libsvm_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_kmeans_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_lda_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_lda_libsvm_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_libsvm_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_linear_regression_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_movielens_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_multiclass_classification_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_svm_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/streaming_kmeans_data_test.txt
spark-3.2.3-bin-hadoop2.7/data/streaming/
spark-3.2.3-bin-hadoop2.7/data/streaming/AFINN-111.txt
spark-3.2.3-bin-hadoop2.7/examples/
spark-3.2.3-bin-hadoop2.7/examples/jars/
spark-3.2.3-bin-hadoop2.7/examples/jars/scopt_2.12-3.7.1.jar
spark-3.2.3-bin-hadoop2.7/examples/jars/spark-examples_2.12-3.2.3.jar
spark-3.2.3-bin-hadoop2.7/examples/src/
spark-3.2.3-bin-hadoop2.7/examples/src/main/
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaHdfsLR.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaLogQuery.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaPageRank.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaSparkPi.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaStatusTrackerDemo.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaTC.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaWordCount.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaAFTSurvivalRegressionExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaALSExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBinarizerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBisectingKMeansExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBucketedRandomProjectionLSHExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBucketizerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaChiSqSelectorExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaChiSquareTestExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaCorrelationExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaCountVectorizerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDCTExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDecisionTreeClassificationExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDecisionTreeRegressionExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDocument.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaElementwiseProductExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaEstimatorTransformerParamExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFMClassifierExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFMRegressorExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFPGrowthExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFeatureHasherExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaGaussianMixtureExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaGeneralizedLinearRegressionExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaGradientBoostedTreeClassifierExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaGradientBoostedTreeRegressorExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaImputerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaIndexToStringExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaInteractionExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaIsotonicRegressionExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaKMeansExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLDAExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLabeledDocument.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLinearRegressionWithElasticNetExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLinearSVCExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLogisticRegressionSummaryExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLogisticRegressionWithElasticNetExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMaxAbsScalerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMinHashLSHExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMinMaxScalerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaModelSelectionViaCrossValidationExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaModelSelectionViaTrainValidationSplitExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMulticlassLogisticRegressionWithElasticNetExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMultilayerPerceptronClassifierExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaNGramExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaNaiveBayesExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaNormalizerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaOneHotEncoderExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaOneVsRestExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPCAExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPipelineExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPolynomialExpansionExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPowerIterationClusteringExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPrefixSpanExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaQuantileDiscretizerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaRFormulaExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaRandomForestClassifierExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaRandomForestRegressorExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaRobustScalerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaSQLTransformerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaStandardScalerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaStopWordsRemoverExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaStringIndexerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaSummarizerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaTfIdfExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaTokenizerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaUnivariateFeatureSelectorExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVarianceThresholdSelectorExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorAssemblerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorIndexerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorSizeHintExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorSlicerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaWord2VecExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaALS.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaAssociationRulesExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaBinaryClassificationMetricsExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaBisectingKMeansExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaChiSqSelectorExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaCorrelationsExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaDecisionTreeClassificationExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaDecisionTreeRegressionExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaElementwiseProductExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaGaussianMixtureExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaGradientBoostingClassificationExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaGradientBoostingRegressionExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaHypothesisTestingExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaHypothesisTestingKolmogorovSmirnovTestExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaIsotonicRegressionExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaKMeansExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaKernelDensityEstimationExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaLBFGSExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaLatentDirichletAllocationExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaLogisticRegressionWithLBFGSExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaMultiLabelClassificationMetricsExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaMulticlassClassificationMetricsExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaNaiveBayesExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaPCAExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaPowerIterationClusteringExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaPrefixSpanExample.java

In [ ]:
!pip install -q findspark

In [ ]:
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.2.3-bin-hadoop2.7"

In [ ]:
import findspark
findspark.init()
from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").getOrCreate()

from pyspark.sql.types import StructType, StructField, IntegerType, StringType

In [ ]:
schema_item = StructType(fields=[
    StructField('movie id', IntegerType()),
    StructField('movie title', StringType()),
    StructField('release date', StringType()),
    StructField('video release date', StringType()),
    StructField('IMDb URL', StringType()),
    StructField('unknown', IntegerType()),
    StructField('Action', IntegerType()),
    StructField('Adventure', IntegerType()),
    StructField('Animation', IntegerType()),
    StructField("'Children's'", IntegerType()),
    StructField('Comedy', IntegerType()),
    StructField('Crime', IntegerType()),
    StructField('Documentary', IntegerType()),
    StructField('Drama', IntegerType()),
    StructField('Fantasy', IntegerType()),
    StructField('Film-Noir', IntegerType()),
    StructField('Horror', IntegerType()),
    StructField('Musical', IntegerType()),
    StructField('Mystery', IntegerType()),
    StructField('Romance', IntegerType()),
    StructField('Sci-Fi', IntegerType()),
    StructField('Thriller', IntegerType()),
    StructField('War', IntegerType()),
    StructField('Western', IntegerType()),
])
df_item=spark.read.csv('u.item.csv', sep = '|', schema = schema_item)
df_item.show(5)

+--------+-----------------+------------+------------------+--------------------+-------+------+---------+---------+------------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|movie id|      movie title|release date|video release date|            IMDb URL|unknown|Action|Adventure|Animation|'Children's'|Comedy|Crime|Documentary|Drama|Fantasy|Film-Noir|Horror|Musical|Mystery|Romance|Sci-Fi|Thriller|War|Western|
+--------+-----------------+------------+------------------+--------------------+-------+------+---------+---------+------------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|       1| Toy Story (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        1|           1|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       2| GoldenEye (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     1|        1|        0|           0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
|       3|Four Rooms (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|           0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
|       4|Get Shorty (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     1|        0|        0|           0|     1|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       5|   Copycat (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|           0|     0|    1|          0|    1|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
+--------+-----------------+------------+------------------+--------------------+-------+------+---------+---------+------------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
only showing top 5 rows

In [ ]:
schema_data = StructType(fields=[
    StructField("user id", IntegerType()),
    StructField("item id", IntegerType()),
    StructField("rating", IntegerType()),
    StructField("timestamp", IntegerType())
])

df_data=spark.read.csv('u.data.csv', sep='\t', schema = schema_data)
df_data.show(5)

+-------+-------+------+---------+
|user id|item id|rating|timestamp|
+-------+-------+------+---------+
|    196|    242|     3|881250949|
|    186|    302|     3|891717742|
|     22|    377|     1|878887116|
|    244|     51|     2|880606923|
|    166|    346|     1|886397596|
+-------+-------+------+---------+
only showing top 5 rows

# 9.Средствами спарка вывести среднюю оценку для каждого фильма

In [ ]:
df_lim_data = df_data.select('item id', 'rating')
df_grp_data=df_lim_data.groupBy('item id')
df_grp_data_avg = df_grp_data.avg('rating')
df_grp_data_avg.sort(['item id'], ascending = True).show(5)

+-------+-----------------+
|item id|      avg(rating)|
+-------+-----------------+
|      1|3.888888888888889|
|      2|           3.0625|
|      3|             3.08|
|      4|3.638095238095238|
|      5|3.326923076923077|
+-------+-----------------+
only showing top 5 rows

# 10.Посчитайте средствами спарка среднюю оценку для каждого жанра

In [ ]:
df_total = df_lim_data
df_total = df_total.join(df_item, df_total['item id'] == df_item['movie id'])
df_total.show(2)
df_genre = df_total.select('movie id', 'rating', 'Action', 'Adventure', 'Animation', "'Children's'", 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western')
df_genre.show(5)
#df_genre.write.format('com.databricks.spark.csv').option('header','true').save('df_genre.csv')

+-------+------+--------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+------------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|item id|rating|movie id|         movie title|release date|video release date|            IMDb URL|unknown|Action|Adventure|Animation|'Children's'|Comedy|Crime|Documentary|Drama|Fantasy|Film-Noir|Horror|Musical|Mystery|Romance|Sci-Fi|Thriller|War|Western|
+-------+------+--------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+------------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|    242|     3|     242|        Kolya (1996)| 24-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|        0|           0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|    302|     3|     302|L.A. Confidential...| 01-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|        0|           0|     0|    1|          0|    0|      0|        1|     0|      0|      1|      0|     0|       1|  0|      0|
+-------+------+--------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+------------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
only showing top 2 rows

+--------+------+------+---------+---------+------------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|movie id|rating|Action|Adventure|Animation|'Children's'|Comedy|Crime|Documentary|Drama|Fantasy|Film-Noir|Horror|Musical|Mystery|Romance|Sci-Fi|Thriller|War|Western|
+--------+------+------+---------+---------+------------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|     242|     3|     0|        0|        0|           0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|     302|     3|     0|        0|        0|           0|     0|    1|          0|    0|      0|        1|     0|      0|      1|      0|     0|       1|  0|      0|
|     377|     1|     0|        0|        0|           1|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|      51|     2|     0|        0|        0|           0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      1|     0|       0|  1|      1|
|     346|     1|     0|        0|        0|           0|     0|    1|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
+--------+------+------+---------+---------+------------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
only showing top 5 rows

In [ ]:
df_Action = df_genre.select('Action', 'rating').filter("Action=='1'")
df_grp_Action=df_Action.groupBy('Action')
df_grp_Action_avg = df_grp_Action.avg('rating').show()

df_Adventure = df_genre.select('Adventure', 'rating').filter("Adventure=='1'")
df_grp_Adventure=df_Adventure.groupBy('Adventure')
df_grp_Adventure_avg = df_grp_Adventure.avg('rating').show()

df_Animation = df_genre.select('Animation', 'rating').filter("Animation=='1'")
df_grp_Animation=df_Animation.groupBy('Animation')
df_grp_Animation_avg = df_grp_Animation.avg('rating').show()

df_Comedy = df_genre.select('Comedy', 'rating').filter("Comedy=='1'")
df_grp_Comedy=df_Comedy.groupBy('Comedy')
df_grp_Comedy_avg = df_grp_Comedy.avg('rating').show()

df_Crime = df_genre.select('Crime', 'rating').filter("Crime=='1'")
df_grp_Crime=df_Crime.groupBy('Crime')
df_grp_Crime_avg = df_grp_Crime.avg('rating').show()

df_Documentary = df_genre.select('Documentary', 'rating').filter("Documentary=='1'")
df_grp_Documentary=df_Documentary.groupBy('Documentary')
df_grp_Documentary_avg = df_grp_Documentary.avg('rating').show()

df_Drama = df_genre.select('Drama', 'rating').filter("Drama=='1'")
df_grp_Drama=df_Drama.groupBy('Drama')
df_grp_Drama_avg = df_grp_Drama.avg('rating').show()

df_Fantasy = df_genre.select('Fantasy', 'rating').filter("Fantasy=='1'")
df_grp_Fantasy=df_Fantasy.groupBy('Fantasy')
df_grp_Fantasy_avg = df_grp_Fantasy.avg('rating').show()

df_Horror = df_genre.select('Horror', 'rating').filter("Horror=='1'")
df_grp_Horror=df_Horror.groupBy('Horror')
df_grp_Horror_avg = df_grp_Horror.avg('rating').show()

df_Musical = df_genre.select('Musical', 'rating').filter("Musical=='1'")
df_grp_Musical=df_Musical.groupBy('Musical')
df_grp_Musical_avg = df_grp_Musical.avg('rating').show()

+------+------------------+
|Action|       avg(rating)|
+------+------------------+
|     1|3.4808126410835216|
+------+------------------+

+---------+------------------+
|Adventure|       avg(rating)|
+---------+------------------+
|        1|3.5026935072299406|
+---------+------------------+

+---------+-----------------+
|Animation|      avg(rating)|
+---------+-----------------+
|        1|3.570203644158628|
+---------+-----------------+

+------+-----------------+
|Comedy|      avg(rating)|
+------+-----------------+
|     1|3.398479708506094|
+------+-----------------+

+-----+------------------+
|Crime|       avg(rating)|
+-----+------------------+
|    1|3.6480917817841254|
+-----+------------------+

+-----------+------------------+
|Documentary|       avg(rating)|
+-----------+------------------+
|          1|3.6733780760626398|
+-----------+------------------+

+-----+------------------+
|Drama|       avg(rating)|
+-----+------------------+
|    1|3.6965510760266893|
+-----+------------------+

+-------+------------------+
|Fantasy|       avg(rating)|
+-------+------------------+
|      1|3.2531468531468533|
+-------+------------------+

+------+------------------+
|Horror|       avg(rating)|
+------+------------------+
|     1|3.3182922596320723|
+------+------------------+

+-------+------------------+
|Musical|       avg(rating)|
+-------+------------------+
|      1|3.5629544584768467|
+-------+------------------+

# 11.В спарке получить 2 датафрейма с 5-ю самыми популярными и самыми непопулярными фильмами (по количеству оценок, либо по самой оценке - на Ваш выбор)

In [ ]:
from pyspark.sql.functions import count as _count

df_rate = df_total.select('item id', 'movie title', 'rating')
df_rate_max = df_rate.groupBy('item id','movie title').agg(_count('rating'))
#Датафрейм с 5-ю самыми популярными фильмами по количеству оценок
df_rate_max.sort(['count(rating)'], ascending = False).show(5)

+-------+--------------------+-------------+
|item id|         movie title|count(rating)|
+-------+--------------------+-------------+
|     50|    Star Wars (1977)|          301|
|    258|      Contact (1997)|          279|
|    100|        Fargo (1996)|          268|
|    288|       Scream (1996)|          266|
|    181|Return of the Jed...|          259|
+-------+--------------------+-------------+
only showing top 5 rows

In [ ]:
#Датафрейм с 5-ю самыми популярными фильмами по суммарной оценке
df_grp_data_sum = df_rate.groupBy('item id','movie title').sum('rating')
df_grp_data_sum.sort(['sum(rating)'], ascending = False).show(5)

+-------+--------------------+-----------+
|item id|         movie title|sum(rating)|
+-------+--------------------+-----------+
|     50|    Star Wars (1977)|       1299|
|    100|        Fargo (1996)|       1123|
|    258|      Contact (1997)|       1073|
|    181|Return of the Jed...|       1036|
|    288|       Scream (1996)|        928|
+-------+--------------------+-----------+
only showing top 5 rows

In [ ]:
#Датафрейм с 5-ю самыми непопулярными фильмами по суммарной оценке
df_grp_data_sum = df_rate.groupBy('item id','movie title').sum('rating')
df_grp_data_sum.sort(['sum(rating)'], ascending = True).show(10)

+-------+--------------------+-----------+
|item id|         movie title|sum(rating)|
+-------+--------------------+-----------+
|   1387|         Fall (1997)|          1|
|   1565|        Daens (1992)|          1|
|   1320|       Homage (1995)|          1|
|    858|Amityville: Dollh...|          1|
|   1342|Convent, The (Con...|          1|
|   1486|Girl in the Cadil...|          1|
|   1340|Crude Oasis, The ...|          1|
|   1572|Wend Kuuni (God's...|          1|
|   1601|Office Killer (1997)|          1|
|   1292|Simple Wish, A (1...|          1|
+-------+--------------------+-----------+
only showing top 10 rows